import { createContext, useContext, useEffect, useMemo, useState } from 'react'

const LanguageContext = createContext(null)

const translations = {
  ca: {
    sessionStarted: 'Sessió iniciada',
    selectLanguage: 'Seleccionar idioma',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Dispositius',
    installations: 'Instal·lacions',
    plants: 'Plantes',
    readings: 'Lectures',
    users: 'Usuaris',
    alerts: 'Alertes',
    settings: 'Configuració',
    clientDetail: 'Detall de client',
    newClient: 'Nou client',
    newClientDescription: 'Crea un nou client de la plataforma.',
    clientDetailDescription: 'Consulta i actualitza la informació del client.',
    backToList: 'Tornar al llistat',
    clientTabGeneral: 'Informació general',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Usuaris',
    clientGeneralInfo: 'Informació general',
    clientAdditionalInfo: 'Informació addicional',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Usuaris del client',
    clientUsersPlaceholder: 'Aquesta pestanya servirà per consultar i gestionar els usuaris associats al client.',
    loadingClient: 'Carregant client...',
    clientLoadError: 'No s’ha pogut carregar el client.',
    clientSaveError: 'No s’ha pogut desar el client.',
    clientSavedSuccess: 'Client actualitzat correctament.',
    clientValidationLegalName: 'El camp "Nom legal" és obligatori.',
    clientValidationTradeName: 'El camp "Nom comercial" és obligatori.',
    clientValidationTaxId: 'El camp "Tax ID" és obligatori.',
    clientValidationEmail: 'El camp "Email" és obligatori.',
    clientValidationPhone: 'El camp "Telèfon" és obligatori.',
    clientValidationClientType: 'El camp "Tipus client" és obligatori.',
    clientValidationApiSecret: 'El camp "Api secret" és obligatori a l’alta.',
    clientCodeAutoHint: 'Es generarà automàticament en desar.',
    automatic: 'Automàtic',
    administration: 'Administració',
    client: 'Client',
    unnamed: 'Sense nom',
    noEmail: 'Sense email',
    yes: 'Sí',
    no: 'No',
    brandPreview: 'Preview de marca',
    example: 'Exemple',
    legalName: 'Nom legal',
    tradeName: 'Nom comercial',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'NIF / CIF',
    phone: 'Telèfon',
    clientType: 'Tipus client',
    active: 'Actiu',
    activeClient: 'Client actiu',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Només s’informa a l’alta del client.',
    apiSecretPlaceholder: 'Secret per generar hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Adreça',
    city: 'Ciutat',
    stateProvince: 'Província / Estat',
    postalCode: 'Codi postal',
    country: 'País',
    notes: 'Notes',
    appName: 'Nom de l’aplicació',
    appNamePlaceholder: 'Ex. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Color primari',
    secondaryColor: 'Color secundari',
    saving: 'Desant...',
    createClient: 'Crear client',
    saveChanges: 'Desar canvis',
    cancel: 'Cancel·lar',
  },
  es: {
    sessionStarted: 'Sesión iniciada',
    selectLanguage: 'Seleccionar idioma',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Dispositivos',
    installations: 'Instalaciones',
    plants: 'Plantas',
    readings: 'Lecturas',
    users: 'Usuarios',
    alerts: 'Alertas',
    settings: 'Configuración',
    clientDetail: 'Detalle de cliente',
    newClient: 'Nuevo cliente',
    newClientDescription: 'Crea un nuevo cliente de la plataforma.',
    clientDetailDescription: 'Consulta y actualiza la información del cliente.',
    backToList: 'Volver al listado',
    clientTabGeneral: 'Información general',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Usuarios',
    clientGeneralInfo: 'Información general',
    clientAdditionalInfo: 'Información adicional',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Usuarios del cliente',
    clientUsersPlaceholder: 'Esta pestaña servirá para consultar y gestionar los usuarios asociados al cliente.',
    loadingClient: 'Cargando cliente...',
    clientLoadError: 'No se ha podido cargar el cliente.',
    clientSaveError: 'No se ha podido guardar el cliente.',
    clientSavedSuccess: 'Cliente actualizado correctamente.',
    clientValidationLegalName: 'El campo "Nombre legal" es obligatorio.',
    clientValidationTradeName: 'El campo "Nombre comercial" es obligatorio.',
    clientValidationTaxId: 'El campo "Tax ID" es obligatorio.',
    clientValidationEmail: 'El campo "Email" es obligatorio.',
    clientValidationPhone: 'El campo "Teléfono" es obligatorio.',
    clientValidationClientType: 'El campo "Tipo de cliente" es obligatorio.',
    clientValidationApiSecret: 'El campo "Api secret" es obligatorio en el alta.',
    clientCodeAutoHint: 'Se generará automáticamente al guardar.',
    automatic: 'Automático',
    administration: 'Administración',
    client: 'Cliente',
    unnamed: 'Sin nombre',
    noEmail: 'Sin email',
    yes: 'Sí',
    no: 'No',
    brandPreview: 'Preview de marca',
    example: 'Ejemplo',
    legalName: 'Nombre legal',
    tradeName: 'Nombre comercial',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'NIF / CIF',
    phone: 'Teléfono',
    clientType: 'Tipo de cliente',
    active: 'Activo',
    activeClient: 'Cliente activo',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Solo se informa en el alta del cliente.',
    apiSecretPlaceholder: 'Secret para generar hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Dirección',
    city: 'Ciudad',
    stateProvince: 'Provincia / Estado',
    postalCode: 'Código postal',
    country: 'País',
    notes: 'Notas',
    appName: 'Nombre de la aplicación',
    appNamePlaceholder: 'Ej. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Color primario',
    secondaryColor: 'Color secundario',
    saving: 'Guardando...',
    createClient: 'Crear cliente',
    saveChanges: 'Guardar cambios',
    cancel: 'Cancelar',
  },
  en: {
    sessionStarted: 'Session started',
    selectLanguage: 'Select language',
    logout: 'Logout',
    dashboard: 'Dashboard',
    device: 'Devices',
    installations: 'Installations',
    plants: 'Plants',
    readings: 'Readings',
    users: 'Users',
    alerts: 'Alerts',
    settings: 'Settings',
    clientDetail: 'Client detail',
    newClient: 'New client',
    newClientDescription: 'Create a new platform client.',
    clientDetailDescription: 'Review and update the client information.',
    backToList: 'Back to list',
    clientTabGeneral: 'General information',
    clientTabBranding: 'Branding',
    clientTabUsers: 'Users',
    clientGeneralInfo: 'General information',
    clientAdditionalInfo: 'Additional information',
    clientBrandingMvp: 'Branding MVP',
    clientUsersTitle: 'Client users',
    clientUsersPlaceholder: 'This tab will be used to review and manage the users associated with the client.',
    loadingClient: 'Loading client...',
    clientLoadError: 'Could not load client.',
    clientSaveError: 'Could not save client.',
    clientSavedSuccess: 'Client updated successfully.',
    clientValidationLegalName: 'The "Legal name" field is required.',
    clientValidationTradeName: 'The "Trade name" field is required.',
    clientValidationTaxId: 'The "Tax ID" field is required.',
    clientValidationEmail: 'The "Email" field is required.',
    clientValidationPhone: 'The "Phone" field is required.',
    clientValidationClientType: 'The "Client type" field is required.',
    clientValidationApiSecret: 'The "Api secret" field is required on create.',
    clientCodeAutoHint: 'It will be generated automatically when saving.',
    automatic: 'Automatic',
    administration: 'Administration',
    client: 'Client',
    unnamed: 'Unnamed',
    noEmail: 'No email',
    yes: 'Yes',
    no: 'No',
    brandPreview: 'Brand preview',
    example: 'Example',
    legalName: 'Legal name',
    tradeName: 'Trade name',
    taxId: 'Tax ID',
    taxIdPlaceholder: 'VAT / Tax ID',
    phone: 'Phone',
    clientType: 'Client type',
    active: 'Active',
    activeClient: 'Active client',
    apiSecret: 'Api secret',
    apiSecretCreateOnly: 'Only informed when creating the client.',
    apiSecretPlaceholder: 'Secret to generate hash',
    website: 'Website',
    externalId: 'External ID',
    address: 'Address',
    city: 'City',
    stateProvince: 'State / Province',
    postalCode: 'Postal code',
    country: 'Country',
    notes: 'Notes',
    appName: 'Application name',
    appNamePlaceholder: 'Ex. Agro Monitor',
    logoUrl: 'Logo URL',
    faviconUrl: 'Favicon URL',
    primaryColor: 'Primary color',
    secondaryColor: 'Secondary color',
    saving: 'Saving...',
    createClient: 'Create client',
    saveChanges: 'Save changes',
    cancel: 'Cancel',
  },
}

const STORAGE_KEY = 'greenlytics_language'

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(
    localStorage.getItem(STORAGE_KEY) || 'ca'
  )

  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, language)
  }, [language])

  const value = useMemo(() => {
    const dict = translations[language] || translations.ca

    return {
      language,
      setLanguage,
      t: (key) => dict[key] || key,
    }
  }, [language])

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)

  if (!context) {
    throw new Error('useLanguage s’ha d’utilitzar dins de LanguageProvider')
  }

  return context
}