namespace GreenLytics.V3.Application.Alerts;

internal static class AlertMapper
{
    public static AlertDto ToDto(this AlertReadModel source)
        => new(
            source.Id,
            source.ClientId,
            source.ClientCode,
            source.ClientName,
            source.InstallationId,
            source.InstallationCode,
            source.InstallationName,
            source.PlantId,
            source.PlantCode,
            source.PlantName,
            source.ReadingTypeId,
            source.ReadingTypeCode,
            source.ReadingTypeName,
            source.ReadingTypeValueType,
            source.Name,
            source.Description,
            source.Channel,
            source.RecipientEmail,
            source.ConditionType,
            source.ValueType,
            source.MinValue,
            source.MaxValue,
            source.ExactNumericValue,
            source.ExactTextValue,
            source.ExactBooleanValue,
            source.IsActive,
            source.CreatedAt,
            source.CreatedByUserId,
            source.UpdatedAt,
            source.UpdatedByUserId);
}

internal sealed record AlertReadModel(
    Guid Id,
    Guid ClientId,
    string? ClientCode,
    string? ClientName,
    Guid? InstallationId,
    string? InstallationCode,
    string? InstallationName,
    Guid? PlantId,
    string? PlantCode,
    string? PlantName,
    Guid ReadingTypeId,
    string ReadingTypeCode,
    string ReadingTypeName,
    string ReadingTypeValueType,
    string Name,
    string? Description,
    string Channel,
    string? RecipientEmail,
    string ConditionType,
    string ValueType,
    decimal? MinValue,
    decimal? MaxValue,
    decimal? ExactNumericValue,
    string? ExactTextValue,
    bool? ExactBooleanValue,
    bool IsActive,
    DateTime CreatedAt,
    Guid? CreatedByUserId,
    DateTime? UpdatedAt,
    Guid? UpdatedByUserId
);
