namespace GreenLytics.V3.Application.Alerts;

public sealed record AlertDto(
    Guid Id,
    Guid ClientId,
    string? ClientCode,
    string? ClientName,
    Guid? InstallationId,
    string? InstallationCode,
    string? InstallationName,
    Guid? PlantId,
    string? PlantCode,
    string? PlantName,
    Guid ReadingTypeId,
    string ReadingTypeCode,
    string ReadingTypeName,
    string ReadingTypeValueType,
    string Name,
    string? Description,
    string Channel,
    string? RecipientEmail,
    string ConditionType,
    string ValueType,
    decimal? MinValue,
    decimal? MaxValue,
    decimal? ExactNumericValue,
    string? ExactTextValue,
    bool? ExactBooleanValue,
    bool IsActive,
    DateTime CreatedAt,
    Guid? CreatedByUserId,
    DateTime? UpdatedAt,
    Guid? UpdatedByUserId
);
